---
  version: "3.8"
  services:
    web:
      image: nginx:1.20-alpine
      volumes:
        - "../../index.html:/usr/share/nginx/html/index.html:ro"
        - "../../styles.css:/usr/share/nginx/html/styles.css:ro"
      ports:
        - "8180:80"
    noted2xero_service:
        image: "phiroict/noted2xero_web:0.3.0"
        ports:
          - "8000:8000"
