---
  version: "3.8"
  services:
    web:
      image: nginx:1.20-alpine
      volumes:
        - "../../index.html:/usr/share/nginx/html/index.html:ro"
        - "../../styles.css:/usr/share/nginx/html/styles.css:ro"
      ports:
        - "8180:80"
    # Version phiroict/noted2xero_web:1.11.10_arm
    noted2xero_service:
        image: "phiroict/noted2xero_web@sha256:2fa3db1536f2774398c9cd0a6df0d2b34552d13d750bbbae9c3513cfb5360d63"
        ports:
          - "8000:8000"
        environment:
          TZ: "Pacific/Auckland"
