---
  version: "3.8"
  services:
    web:
      image: nginx:1.20-alpine
      volumes:
        - "../../index.html:/usr/share/nginx/html/index.html:ro"
        - "../../styles.css:/usr/share/nginx/html/styles.css:ro"
      ports:
        - "8180:80"
    # Version phiroict/noted2xero_web:1.11.0_arm
    noted2xero_service:
        image: "phiroict/noted2xero_web@sha256:df9d2f26a29a29b6550ed15005f9b75113e20c2ef67560edfece04823adf5bd8"
        ports:
          - "8000:8000"
        environment:
          TZ: "Pacific/Auckland"
