apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: noted2xero
  name: noted2xero
  namespace: apps-noted-xero
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: noted2xero
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:      
      labels:
        app: noted2xero
    spec:
      containers:
        - image: phiroict/noted2xero_web:0.3.4
          imagePullPolicy: Always
          name: noted2xero-web-lvxq7
          livenessProbe:
            httpGet:
              port: 8000
              path: /healthcheck
              scheme: HTTP
          resources:
            limits:
              memory: 1Gi
              cpu: 10m
            requests:
              memory: 1Gi
              cpu: 10m
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          securityContext:
            runAsNonRoot: false
            allowPrivilegeEscalation: false
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsNonRoot: true
      terminationGracePeriodSeconds: 30
