---
apiVersion: v1
kind: Service
metadata:
  name: noted-frontend-service
  namespace: apps-noted-xero
spec:
  selector:
    app: noted-frontend
  ports:
  - port: 80
    targetPort: 8080
    name: http-xerowebport

