apiVersion: v1
kind: Service
metadata:
  name: xero-web-service
  namespace: apps-noted-xero
spec:
  selector:
    app: noted2xero
  ports:
  - port: 8000
    targetPort: 8000
    name: http-noted2xeroport
