FROM ubuntu as builder
RUN apt update && apt upgrade -y && apt install build-essential curl -y
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y
RUN /root/.cargo/bin/rustup install nightly
ADD . .
RUN /root/.cargo/bin/rustup override set nightly
RUN /root/.cargo/bin/cargo test
RUN /root/.cargo/bin/cargo build --release
FROM ubuntu
RUN mkdir /app
WORKDIR /app
COPY --from=builder /target/release/noted2xero_web noted2xero_web
COPY --from=builder noted2xero_web/Rocket.toml Rocket.toml
CMD ./noted2xero_web

