FROM rust:1.69.0-slim-buster as builder
RUN mkdir -p /src
WORKDIR /src
COPY . .
RUN rustup override set nightly && cargo test && cargo build --release

FROM debian:buster-slim
RUN mkdir /app
WORKDIR /app
COPY --from=builder /src/target/release/noted2xero_web noted2xero_web
COPY --from=builder /src/Rocket.toml Rocket.toml
CMD ["./noted2xero_web"]

