apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"1"},"creationTimestamp":"2021-05-15T03:44:53Z","generation":3,"labels":{"app":"noted2xero"},"name":"noted2xero","namespace":"default","resourceVersion":"3189","uid":"57c7b8f9-34ca-4919-9f18-5c73cd5d9eec"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"noted2xero"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"noted2xero"}},"spec":{"containers":[{"image":"phiroict/noted2xero_web:0.3.0","imagePullPolicy":"IfNotPresent","name":"noted2xero-web-lvxq7","resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{"availableReplicas":1,"conditions":[{"lastTransitionTime":"2021-05-15T03:44:55Z","lastUpdateTime":"2021-05-15T03:44:55Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"},{"lastTransitionTime":"2021-05-15T03:44:53Z","lastUpdateTime":"2021-05-15T03:44:55Z","message":"ReplicaSet \"noted2xero-6dc6c564ff\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"}],"observedGeneration":3,"readyReplicas":1,"replicas":1,"updatedReplicas":1}}
    kubernetes.io/change-cause: kubectl set image deployment/noted2xero noted2xero-6dc6c564ff-8cw5q=phiroict/noted2xero_web:0.3.1
      --record=true
  creationTimestamp: "2021-05-15T03:44:53Z"
  generation: 7
  labels:
    app: noted2xero
  name: noted2xero
  namespace: default
  resourceVersion: "3628"
  uid: 57c7b8f9-34ca-4919-9f18-5c73cd5d9eec
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: noted2xero
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: noted2xero
    spec:
      containers:
      - image: phiroict/noted2xero_web:0.3.0
        imagePullPolicy: IfNotPresent
        name: noted2xero-web-lvxq7
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-05-15T03:44:55Z"
    lastUpdateTime: "2021-05-15T03:44:55Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-05-15T03:44:53Z"
    lastUpdateTime: "2021-05-15T03:44:55Z"
    message: ReplicaSet "noted2xero-6dc6c564ff" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 7
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
