---
apiVersion: v1
kind: Namespace
metadata:
  name: apps-noted-xero
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: noted-frontend
  name: noted-frontend
  namespace: apps-noted-xero
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: noted-frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: noted-frontend
    spec:
      containers:
        - image: phiroict/xero_frontend@sha256:6826cf14e8b2feb2c119cb7fd693fddb75fac1c81e5a0e6903834d5c9c007748
          imagePullPolicy: Always
          name: noted-frontend
          resources:
            limits:
              memory: 256 MiB
              cpu: 10m
            requests:
              memory: 128 MiB
              cpu: 10m
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          livenessProbe:
            initialDelaySeconds: 20
            httpGet:
              port: 80
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsNonRoot: true
      terminationGracePeriodSeconds: 30

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: noted2xero
  name: noted2xero
  namespace: apps-noted-xero
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: noted2xero
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: noted2xero
    spec:
      containers:
        - image: phiroict/noted2xero_web:0.3.4
          imagePullPolicy: Always
          name: noted2xero-web-lvxq7
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          livenessProbe:
            initialDelaySeconds: 20
            httpGet:
              port: 8000
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsNonRoot: true
      terminationGracePeriodSeconds: 30
