---
apiVersion: v1
kind: Namespace
metadata:
  name: apps-noted-xero
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: noted-frontend
  name: noted-frontend
  namespace: apps-noted-xero
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: noted-frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: noted-frontend
    spec:
      containers:
        # Version 0.4.0-rc3
        - image: phiroict/noted2xero_web@sha256:104cf978b70154c63a7749e4d1c4cfb5ec8f17593cd21afdec101a24c822c11b
          imagePullPolicy: Always
          name: noted-frontend
          resources:
            limits:
              memory: "256Mi"
              cpu: "10m"
            requests:
              memory: "128Mi"
              cpu: "10m"
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          livenessProbe:
            initialDelaySeconds: 20
            tcpSocket:
              port: 8000
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
          readinessProbe:
            httpGet:
              scheme: HTTP
              port: 8000
              path: healthcheck
            failureThreshold: 3
            initialDelaySeconds: 10
            timeoutSeconds: 30
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: note2xero-srv
  namespace: apps-noted-xero
spec:
  type: NodePort
  selector:
    app: noted-frontend
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      nodePort: 30002
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
  namespace: apps-noted-xero
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /noted
            pathType: Prefix
            backend:
              service:
                name: note2xero-srv
                port:
                  number: 80

#---
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  labels:
#    app: noted2xero
#  name: noted2xero
#  namespace: apps-noted-xero
#spec:
#  progressDeadlineSeconds: 600
#  replicas: 1
#  revisionHistoryLimit: 10
#  selector:
#    matchLabels:
#      app: noted2xero
#  strategy:
#    rollingUpdate:
#      maxSurge: 25%
#      maxUnavailable: 25%
#    type: RollingUpdate
#  template:
#    metadata:
#      creationTimestamp: null
#      labels:
#        app: noted2xero
#    spec:
#      containers:
#        - image: phiroict/noted2xero_web:0.4.0-rc1
#          imagePullPolicy: Always
#          name: noted2xero-web
#          resources: {}
#          terminationMessagePath: /dev/termination-log
#          terminationMessagePolicy: File
#          livenessProbe:
#            initialDelaySeconds: 20
#            httpGet:
#              port: 8000
#          securityContext:
#            allowPrivilegeEscalation: false
#            readOnlyRootFilesystem: false
#      dnsPolicy: ClusterFirst
#      restartPolicy: Always
#      schedulerName: default-scheduler
#      securityContext:
#        runAsNonRoot: true
#      terminationGracePeriodSeconds: 30
